# Generated by Django 5.0.1 on 2024-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_objectif_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
