# Generated by Django 5.0.1 on 2024-02-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_language_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
