# Generated by Django 4.2.2 on 2024-03-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0009_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cni',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email_author',
            field=models.EmailField(default='Tighri', max_length=254),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
